#model:
# The quantity of steps in the diffusion process
T: 200
# Quantity of samples to use when approximating the loss
num_sample_steps: 10

#training:
# Quantity of training epochs
epochs: 3
# Learning rate
lr: 0.01
# How frequently to checkpoint the model
save_every_n_epochs: 10
# The quantity of examples to print during training
num_examples: 64
# The total quantity of samples to use when validating the model
num_val_samples: 128
# the quantity of samples to take at a time when validating the model
val_batch_size: 64
# The threshold for grad_clip_norm
clip_thresh: 1.0

sequence_length: 784

#data:
# Quantity of training samples per minibatch
batch_size: 64